name: JUnit-Frontends

on: pull_request
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: JUnit-Frontends
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Test Maven Build
      run: cd frontends/java && mvn --batch-mode -DskipTests clean package
    - name: Unit Test (defer fail report)
      run: cd frontends/java && mvn --batch-mode -Dmaven.test.failure.ignore=true test
    - name: Report unit test result
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Build / Unit Test
        path: frontends/java/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
